version: 2.1

jobs:
  works-job:
    working_directory: ~/Lets_walk-website/app
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout:
          path: ~/Lets_walk-website
      - run: echo "hello world"
      - run: npm install
      - run: npm test

workflows:
  my-workflow:
    jobs:
      - works-job
